version: '3.5'

services:
  mongo-data:
    container_name: crawler_mongo
    image: mongo:4.4.4
    ports:
      - "127.0.0.1:27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - type: volume
        source: mongo-data-db
        target: /data/db

  postgres:
    container_name: crawler_postgres
    image: postgis/postgis:13-3.1-alpine
    ports:
      - "127.0.0.1:5433:5432"
    environment:
      POSTGRES_PASSWORD: 'postgres'

  crawler-processor:
    container_name: crawler_processor
    build: ./build/docker/
    image: processor:0.0.0
    volumes:
      - ./logs:/logs

volumes:
  mongo-data-db:
